// Русские подписи только для отображения исторической таблицы. Исходные данные не меняются.
const translations: Readonly<Record<string, string>> = {
  "CLR_shape_only": "Только форма в пространстве CLR",
  "log_Total_only": "Только логарифм Total",
  "mixed L+h+CLR4": "Смешанное пространство L+h+CLR4",
  "mixed_L_h_CLR": "Смешанное пространство L, h и CLR",
  "original mixed X6": "Исходное смешанное пространство X6",
  "raw positive selected5 cosine": "Косинусное сходство положительных исходных расходов по 5 выбранным категориям",
  "saved original X[:,2:];CLR4 only": "Сохранённые исходные X[:,2:]; только CLR4",
  "shape CLR4": "Форма в пространстве CLR4",
  "2023-01..2024-12": "2023-01 — 2024-12",
  "2023-12;2024-12": "2023-12; 2024-12",
  "2024-03;06;09;12": "Опорные месяцы: 2024-03; 06; 09; 12",
  "full observed in two anchor months": "Полная наблюдаемая опора двух опорных месяцев",
  "native observed anchors;2 fixed-reference 80% draws/anchor": "Наблюдаемая опора каждого опорного месяца; 2 подвыборки по 80% с фиксированным эталоном на месяц",
  "native observed per month; catalog2190;50521 ID-months": "Наблюдаемая опора каждого месяца; каталог 2190 ID; 50521 наблюдение ID × месяц",
  "native observed quarter anchors; 2 fixed-reference 80% draws/anchor": "Наблюдаемая опора квартальных опорных месяцев; 2 подвыборки по 80% с фиксированным эталоном на месяц",
  "native observed; radius variant partial in 2023-09": "Наблюдаемая опора; радиусный вариант имеет неполное присвоение в 2023-09",
  "same saved full-support partitions": "Те же сохранённые разбиения на полной опоре",
  "common original X6/Y7/radius1.5": "Общая исходная геометрия X6/Y7; радиус 1.5",
  "fixed common mixed X6/Y7/radius1.5": "Фиксированная общая смешанная геометрия X6/Y7; радиус 1.5",
  "fixed common mixed geometry; historical selector differs from DT24": "Фиксированная общая смешанная геометрия; исторический отбор отличается от DT24",
  "mixed": "Смешанная геометрия",
  "shape": "Геометрия формы",
  "cos(c_i,c_j); raw RUB selected5; scale invariant; edge weight cosine": "cos(c_i,c_j); исходные расходы в рублях по 5 выбранным категориям; не зависит от масштаба; вес ребра — косинусное сходство",
  "d2=0.5*dL2/sL2+0.25*dh2/sh2+0.25*norm(dR)2/sR2": "d2=0.5*dL2/sL2+0.25*dh2/sh2+0.25*norm(dR)2/sR2",
  "mixed alpha0.25 beta0.5": "Смешанное сходство: alpha0.25 beta0.5",
  "mixed alpha0.5 beta0.5": "Смешанное сходство: alpha0.5 beta0.5",
  "original mixed distance": "Исходное смешанное расстояние",
  "original scaled CLR4 distance; no new scale": "Исходное нормированное расстояние CLR4; масштаб заново не оценивался",
  "shape-only distance": "Расстояние только по форме",
  "complete_Gaussian_sigma1": "Полный граф с гауссовыми весами, sigma1",
  "mutual15 Gaussian sigma1; no isolate repair": "Взаимные 15 ближайших соседей; гауссовы веса, sigma1; изолированные узлы не корректировались",
  "no fitting graph": "Нет графа обучения",
  "no_fitting_graph": "Нет графа обучения",
  "none": "Нет графа обучения",
  "radius1.5_Gaussian_sigma1": "Радиус 1.5; гауссовы веса, sigma1",
  "union10 Gaussian": "Объединение списков 10 ближайших соседей; гауссовы веса",
  "union15 Gaussian": "Объединение списков 15 ближайших соседей; гауссовы веса",
  "union15 Gaussian sigma1": "Объединение списков 15 ближайших соседей; гауссовы веса, sigma1",
  "union15 exact cosine ties": "Объединение списков 15 ближайших соседей по косинусному сходству с сохранением точных равенств",
  "union15 including exact kth ties; Gaussian sigma1": "Объединение списков 15 ближайших соседей с точными равенствами на границе k; гауссовы веса, sigma1",
  "union15; local-rho7 Gaussian scale": "Объединение списков 15 ближайших соседей; локальный гауссов масштаб rho7",
  "union20 Gaussian": "Объединение списков 20 ближайших соседей; гауссовы веса",
  "union30 all exact kth ties;Gaussian sigma1": "Объединение списков 30 ближайших соседей со всеми точными равенствами на границе k; гауссовы веса, sigma1",
  "union_kNN15_Gaussian_sigma1": "Объединение kNN15; гауссовы веса, sigma1",
  "evaluator_sensitivity": "Чувствительность к оценочной геометрии",
  "graph_topology_or_weight_with_same_X": "Топология или веса графа при том же X",
  "neighbour_count": "Число ближайших соседей",
  "partition_algorithm_at_fixed_similarity": "Алгоритм разбиения при фиксированном определении сходства",
  "remove_level_and_h": "Исключение уровня расходов и контраста h",
  "representation_or_graph_rule_historical": "Историческое сравнение пространств признаков или правил построения графа",
  "similarity_definition_at_K2": "Определение сходства при K2",
  "K2 cannot establish detailed K10 behavior; radius ID344 unassigned in 2023-09; do not rank partial support as complete": "Сравнение при K2 не подтверждает поведение подробного K10; в радиусном варианте ID344 не получил группу в 2023-09; неполную опору нельзя ранжировать как полную",
  "K20 mean macroJ improves but joint worst-month SW gate fails; no automatic expansion": "Средний macroJ при K20 выше, но совместный критерий SW худшего месяца не пройден; число групп автоматически не увеличивается",
  "S_Dbw finite-only means not directly ranked; mean stability does not remove weak groups": "Средние S_Dbw только по конечным значениям напрямую не ранжируются; средняя устойчивость не устраняет слабые группы",
  "all six metrics finite is not sufficient for promotion; common evaluator answers mixed question": "Конечных значений всех шести индексов недостаточно для выбора варианта; оценка в общей геометрии относится к смешанному пространству",
  "not DT24 end-to-end stability; unavailable scores blank, not zero; no own-NCut cross-graph ranking": "Это не сквозная оценка устойчивости DT24; недоступные оценки оставлены пустыми, а не нулевыми; разбиения собственного NCut не ранжируются на разных графах",
  "two months,K2; not a 24-month or K10 result": "Два месяца, K2; это не результат за 24 месяца или для K10",
  "win counts only within evaluator; no numerical score comparison across evaluators; not current K10 evidence": "Победы считаются только в рамках одной оценочной геометрии; численные оценки разных геометрий не сравниваются; это не подтверждение текущего K10",
  "control": "Контрольный вариант",
  "historical diagnostic; not current K10 choice": "Историческая диагностика; это не текущий выбор K10",
  "mandatory strong geometry comparator": "Обязательный сильный геометрический контроль",
  "quality gate FAIL": "Критерий качества не пройден",
  "retained diagnostic control": "Сохранённый диагностический контроль",
  "selected primary descriptive network layer": "Выбран основной описательный сетевой слой",
  "sensitivity only; no K10 promotion": "Только проверка чувствительности; оснований для выбора K10 нет",
  "shape SW wins 0/24,0/24,0/24,0/24 against four controls": "Победы SW в геометрии формы: 0/24, 0/24, 0/24, 0/24 при сравнении с четырьмя контрольными вариантами",
  "shape SW wins 24/24,24/24,24/24,24/24 against four controls": "Победы SW в геометрии формы: 24/24, 24/24, 24/24, 24/24 при сравнении с четырьмя контрольными вариантами",
  "unavailable due to isolates": "Недоступно из-за изолированных узлов",
  "4 anchors x2 80% draws; reference fixed": "4 опорных месяца × 2 подвыборки по 80%; эталон фиксирован",
  "4 anchors x2 80% draws;reference fixed": "4 опорных месяца × 2 подвыборки по 80%; эталон фиксирован",
  "6 anchors x10 80% draws; 24-month reference re-fit on draw IDs; end-to-end": "6 опорных месяцев × 10 подвыборок по 80%; эталон за 24 месяца заново обучен на ID подвыборки; сквозная проверка"
}

/** Неизвестные строки сохраняются целиком, без догадок и подмены идентификаторов. */
export function displayEvidenceText(text: string | undefined): string {
  if (text === undefined) return ''
  return Object.hasOwn(translations, text) ? (translations[text] ?? text) : text
}
